### ISSUE TITLE
Not Working with ioredis

### ISSUE THREAD

**Issue by koolkarni** [arjunmehta/node-georedis#10]
## **Not providing proper long and lat :**

From Location() api =>  null { latitude: 43.64728555083275, longitude: -79.40306156873703 }
nearby locations: { '4': { key: [ '4' ], latitude: null, longitude: null },
  null: { key: null, latitude: null, longitude: null },
  '': { key: [], latitude: null, longitude: null } }
Got Data from Paged Results  []
## Providing same results for all the nearBy locations

nearby locations: [ { latitude: -89.99999865889549,
    longitude: -179.99999731779099,
    key: 'null' } ]

**Comment by tte** [comment]
Same multiple issues - `ioredis` not yet compatible w/ this lib.

**UPD:**
@koolkarni Looks like `ioredis` support native geo module since redis 3.2 released. Gonna check and migrate.

**Comment by arjunmehta** [comment]
ioredis support in v3.1.0
