### ISSUE TITLE
Generating commands for use in redis-cli

### ISSUE THREAD

**Issue by mikezliu** [arjunmehta/node-georedis#17]
I'm bulk importing millions of geos and other keys and would like to do this via a single file generated using the redis protocol (http://redis.io/topics/mass-insert).  Is there a way to generate the georedis insert/set commands?

**Comment by arjunmehta** [comment]
@mikezliu You can definitely look at the code to see how I'm generating the query here https://github.com/arjunmehta/node-georedis/blob/master/lib/interfaceNative.js#L20-L32

You'll need to consider how to apply that to your project.
