### ISSUE TITLE
coordinates entered are not exactly same as original

### ISSUE THREAD

**Issue by vvavepacket** [arjunmehta/node-georedis#19]
Lets say we have the following coordinate which we want to add

longitude,latitude
121.16625075805472,14.55976969490166

Now, if we try to insert it using node-georedis, it was inserted successfully, but the inserted coordinates are different from original. Why is that?

longitude,latitude
121.16625219583511353,14.55976912035422544

**Comment by arjunmehta** [comment]
Hi @vvavepacket 
Yes, both the native (redis/c++) and emulated (javascript) methods of storing the coordinates use **geohashing**, which is only precise up to a certain number of decimal places. Both are limited by the maximum system floating point (64bit for c++, 52 for javascript).

In fact geohashes are actually just boxes of a certain accuracy.

You can learn more about the general algorithm used by this module [here](http://gis.stackexchange.com/questions/18330/would-it-be-possible-to-use-geohash-for-proximity-searches/92331#92331) and also learn about [geohashing here](https://en.wikipedia.org/wiki/Geohash).
