### ISSUE TITLE
Requesting a new release to NPM

### ISSUE THREAD

**Issue by severi** [arjunmehta/node-georedis#21]
Hi,

Would it be possible to publish a new release to NPM registry? The current release (3.0.3) is already one year old and is missing for example the following commit: https://github.com/arjunmehta/node-georedis/commit/bbf88ba61f9b2561f099ee47b2b04d3e16d75f6d. Without the fix introduced in the commit the module crashes if the "geo.location" function is called for an id that is not present or has already been deleted.

Thanks! :)

**Comment by arjunmehta** [comment]
@severi You're right! Thanks for the nudge. Just published to npm and tagged and released in git.
Please let me know if this resolves the issue and close the issue if so.

Thanks again

**Comment by severi** [comment]
The issue was solved, thanks a lot!
