### ISSUE TITLE
pubnub malforms location coordinate latitude values

### ISSUE THREAD

**Issue by richacker** [arjunmehta/node-georedis#22]
Hi,

I am trying to store the lat long as:
{"lat":29.419506,"long":79.038539}

But on querying the position, it returns:
27.80180134535769554 79.03853863477706909

Same is the case with any other position. Also the variation is not fixed.

**Comment by arjunmehta** [comment]
@richacker thanks for submitting the issue. Can you tell me whether you're using the native Reid's implementation or the emulated?

Thanks!

**Comment by richacker** [comment]
Hi, I am using emulated. Although on debugging I discovered that the issue is only on the case when I am inside the Pubnub listener. My code looks like this:

`pubnub.addListener({
    message: function(message) {
        if (message.channel && message.channel.indexOf("gridapp.locations.") != -1) {
            let userId = message.channel.split("gridapp.locations.")[1];
            console.log(message);
            let coordinates = typeof message.message == "object" ? message.message : JSON.parse(message.message);
            console.log(userId);
            console.log(coordinates.lat);
            console.log(coordinates.long);
            var redis = require('redis'),
                client = redis.createClient()
            var geo = require('georedis').initialize(client);
            console.log({ latitude: coordinates.lat, longitude: coordinates.long });


            geo.addLocation('Toronto', { latitude: 43.6667, longitude: -79.4167 }, function(err, reply) {
                if (err) console.error(err)
                else console.log('added location:', reply)
            })

        }
        //console.log("New Message!!", message);
    }
})`

And on fetching the response is:
Location for Toronto is:  41.26557858154362179 -79.4166979193687439

**Comment by arjunmehta** [comment]
@richacker Ahhh, very strange. Are you saying it works normally if you call `addLocation` outside of the `pubnub.addListener`?

**Comment by arjunmehta** [comment]
Also I should say, you should only initialize the module once...

Could you try changing your code to look more like:

```javascript
var redis = require('redis');
var client = redis.createClient();
var geo = require('georedis').initialize(client);

pubnub.addListener({
    message: function(message) {
        if (message.channel && message.channel.indexOf("gridapp.locations.") != -1) {
            geo.addLocation('Toronto', { latitude: 43.6667, longitude: -79.4167 }, function(err, reply) {
                if (err) console.error(err)
                else console.log('added location:', reply)
            })
        }
    }
})
```

**Comment by richacker** [comment]
@arjunmehta I understand your concern for initializing the module once, but it throws the error:
-ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

And yes it works fine in normal context and only when it is in subscriber mode for pubnub listener or even in case of socket.io listeners, it shows this anomaly.

**Comment by arjunmehta** [comment]
I think this may be an issue with pubnub. I misunderstood, and didn't realize that you weren't using standard redis pub/sub.

Closing this issue as an edge case. Can open again if reported by others.
