### ISSUE TITLE
withDistances doesn't respect `units` parameter

### ISSUE THREAD

**Issue by jesseditson** [arjunmehta/node-georedis#3]
Hey! I noticed that when doing a query like:

```
geo.nearby(location, 0.5, { withDistances: true, units: 'mi' }, function(err, locations) {
    // locations contain a distance key, but the distance is in meters
})
```

Not a big deal (I can do the conversion on my side), but I figured it might be nice to have the units be consistent if it's an easy change.

**Comment by arjunmehta** [comment]
Hey there @jesseditson 

Thanks so much for reporting this.
Can you confirm a few things?

Are you using the nativeGeo mode? (ie. do you have redis 3.1.199 or higher?)
If not, were you using the `accurate` option?  I found a bug in the code where I forgot to convert units, but only when in accurate mode.

**Comment by jesseditson** [comment]
Hey! I'm using `accurate`, and I'm not using native yet - currently on `v2.8.19`, so it sounds like I'm experiencing the exact bug you mentioned!

**Comment by arjunmehta** [comment]
Oh perfect. I'll fix and publish in a sec.

**Comment by arjunmehta** [comment]
Published! Give it a try.

**Comment by jesseditson** [comment]
Awesome! I'll bump my version and test it out!

**Comment by jesseditson** [comment]
This looks good on my end! Seems to be fixed by https://github.com/arjunmehta/node-georedis/commit/2a564c333c0f129c15e90fec05a30e9fe34435cc. Thanks a bunch!

**Comment by arjunmehta** [comment]
Awesome. Thanks for reporting the bug!
