### ISSUE TITLE
Add additional properties?

### ISSUE THREAD

**Issue by komocode** [arjunmehta/node-georedis#6]
I need to save additional data ("authorID" and "workshopID") to the locations saved. Right now there's only a field for the 'locationName'. The only way I can save the extra data is if I save a JSON as a string into the locationName field. This means I have to parse each locationName as a JSON when I retrieve the location. Is there any other way to do this?

**Comment by arjunmehta** [comment]
@komocode Ah, yes this is beyond the scope of this project, I think and would significantly change the architecture. You would normally have another set you could look up data based on location names.

It's neat that you are using JSON encoding to store that info though :) Crafty!
